module LocalAuthorityDistrict
  ENGLAND = [
    { code: 'E06000001', name: 'Hartlepool',                          region: 'NE' },
    { code: 'E06000002', name: 'Middlesbrough',                       region: 'NE' },
    { code: 'E06000003', name: 'Redcar and Cleveland',                region: 'NE' },
    { code: 'E06000004', name: 'Stockton-on-Tees',                    region: 'NE' },
    { code: 'E06000005', name: 'Darlington',                          region: 'NE' },
    { code: 'E06000006', name: 'Halton',                              region: 'NW' },
    { code: 'E06000007', name: 'Warrington',                          region: 'NW' },
    { code: 'E06000008', name: 'Blackburn with Darwen',               region: 'NW' },
    { code: 'E06000009', name: 'Blackpool',                           region: 'NW' },
    { code: 'E06000010', name: 'Kingston upon Hull, City of',         region: 'YH' },
    { code: 'E06000011', name: 'East Riding of Yorkshire',            region: 'YH' },
    { code: 'E06000012', name: 'North East Lincolnshire',             region: 'YH' },
    { code: 'E06000013', name: 'North Lincolnshire',                  region: 'YH' },
    { code: 'E06000014', name: 'York',                                region: 'YH' },
    { code: 'E06000015', name: 'Derby',                               region: 'EM' },
    { code: 'E06000016', name: 'Leicester',                           region: 'EM' },
    { code: 'E06000017', name: 'Rutland',                             region: 'EM' },
    { code: 'E06000018', name: 'Nottingham',                          region: 'EM' },
    { code: 'E06000019', name: 'Herefordshire, County of',            region: 'WM' },
    { code: 'E06000020', name: 'Telford and Wrekin',                  region: 'WM' },
    { code: 'E06000021', name: 'Stoke-on-Trent',                      region: 'WM' },
    { code: 'E06000022', name: 'Bath and North East Somerset',        region: 'SW' },
    { code: 'E06000023', name: 'Bristol, City of',                    region: 'SW' },
    { code: 'E06000024', name: 'North Somerset',                      region: 'SW' },
    { code: 'E06000025', name: 'South Gloucestershire',               region: 'SW' },
    { code: 'E06000026', name: 'Plymouth',                            region: 'SW' },
    { code: 'E06000027', name: 'Torbay',                              region: 'SW' },
    { code: 'E06000030', name: 'Swindon',                             region: 'SW' },
    { code: 'E06000031', name: 'Peterborough',                        region: 'E' },
    { code: 'E06000032', name: 'Luton',                               region: 'E' },
    { code: 'E06000033', name: 'Southend-on-Sea',                     region: 'E' },
    { code: 'E06000034', name: 'Thurrock',                            region: 'E' },
    { code: 'E06000035', name: 'Medway',                              region: 'SE' },
    { code: 'E06000036', name: 'Bracknell Forest',                    region: 'SE' },
    { code: 'E06000037', name: 'West Berkshire',                      region: 'SE' },
    { code: 'E06000038', name: 'Reading',                             region: 'SE' },
    { code: 'E06000039', name: 'Slough',                              region: 'SE' },
    { code: 'E06000040', name: 'Windsor and Maidenhead',              region: 'SE' },
    { code: 'E06000041', name: 'Wokingham',                           region: 'SE' },
    { code: 'E06000042', name: 'Milton Keynes',                       region: 'SE' },
    { code: 'E06000043', name: 'Brighton and Hove',                   region: 'SE' },
    { code: 'E06000044', name: 'Portsmouth',                          region: 'SE' },
    { code: 'E06000045', name: 'Southampton',                         region: 'SE' },
    { code: 'E06000046', name: 'Isle of Wight',                       region: 'SE' },
    { code: 'E06000047', name: 'County Durham',                       region: 'NE' },
    { code: 'E06000049', name: 'Cheshire East',                       region: 'NW' },
    { code: 'E06000050', name: 'Cheshire West and Chester',           region: 'NW' },
    { code: 'E06000051', name: 'Shropshire',                          region: 'WM' },
    { code: 'E06000052', name: 'Cornwall',                            region: 'SW' },
    { code: 'E06000053', name: 'Isles of Scilly',                     region: 'SW' },
    { code: 'E06000054', name: 'Wiltshire',                           region: 'SW' },
    { code: 'E06000055', name: 'Bedford',                             region: 'E' },
    { code: 'E06000056', name: 'Central Bedfordshire',                region: 'E' },
    { code: 'E06000057', name: 'Northumberland',                      region: 'NE' },
    { code: 'E06000058', name: 'Bournemouth, Christchurch and Poole', region: 'SW' },
    { code: 'E06000059', name: 'Dorset',                              region: 'SW' },
    { code: 'E06000060', name: 'Buckinghamshire',                     region: 'SE' },
    { code: 'E06000061', name: 'North Northamptonshire',              region: 'EM' },
    { code: 'E06000062', name: 'West Northamptonshire',               region: 'EM' },
    { code: 'E07000008', name: 'Cambridge',                           region: 'E' },
    { code: 'E07000009', name: 'East Cambridgeshire',                 region: 'E' },
    { code: 'E07000010', name: 'Fenland',                             region: 'E' },
    { code: 'E07000011', name: 'Huntingdonshire',                     region: 'E' },
    { code: 'E07000012', name: 'South Cambridgeshire',                region: 'E' },
    { code: 'E07000026', name: 'Allerdale',                           region: 'NW' },
    { code: 'E07000027', name: 'Barrow-in-Furness',                   region: 'NW' },
    { code: 'E07000028', name: 'Carlisle',                            region: 'NW' },
    { code: 'E07000029', name: 'Copeland',                            region: 'NW' },
    { code: 'E07000030', name: 'Eden',                                region: 'NW' },
    { code: 'E07000031', name: 'South Lakeland',                      region: 'NW' },
    { code: 'E07000032', name: 'Amber Valley',                        region: 'EM' },
    { code: 'E07000033', name: 'Bolsover',                            region: 'EM' },
    { code: 'E07000034', name: 'Chesterfield',                        region: 'EM' },
    { code: 'E07000035', name: 'Derbyshire Dales',                    region: 'EM' },
    { code: 'E07000036', name: 'Erewash',                             region: 'EM' },
    { code: 'E07000037', name: 'High Peak',                           region: 'EM' },
    { code: 'E07000038', name: 'North East Derbyshire',               region: 'EM' },
    { code: 'E07000039', name: 'South Derbyshire',                    region: 'EM' },
    { code: 'E07000040', name: 'East Devon',                          region: 'SW' },
    { code: 'E07000041', name: 'Exeter',                              region: 'SW' },
    { code: 'E07000042', name: 'Mid Devon',                           region: 'SW' },
    { code: 'E07000043', name: 'North Devon',                         region: 'SW' },
    { code: 'E07000044', name: 'South Hams',                          region: 'SW' },
    { code: 'E07000045', name: 'Teignbridge',                         region: 'SW' },
    { code: 'E07000046', name: 'Torridge',                            region: 'SW' },
    { code: 'E07000047', name: 'West Devon',                          region: 'SW' },
    { code: 'E07000061', name: 'Eastbourne',                          region: 'SE' },
    { code: 'E07000062', name: 'Hastings',                            region: 'SE' },
    { code: 'E07000063', name: 'Lewes',                               region: 'SE' },
    { code: 'E07000064', name: 'Rother',                              region: 'SE' },
    { code: 'E07000065', name: 'Wealden',                             region: 'SE' },
    { code: 'E07000066', name: 'Basildon',                            region: 'E' },
    { code: 'E07000067', name: 'Braintree',                           region: 'E' },
    { code: 'E07000068', name: 'Brentwood',                           region: 'E' },
    { code: 'E07000069', name: 'Castle Point',                        region: 'E' },
    { code: 'E07000070', name: 'Chelmsford',                          region: 'E' },
    { code: 'E07000071', name: 'Colchester',                          region: 'E' },
    { code: 'E07000072', name: 'Epping Forest',                       region: 'E' },
    { code: 'E07000073', name: 'Harlow',                              region: 'E' },
    { code: 'E07000074', name: 'Maldon',                              region: 'E' },
    { code: 'E07000075', name: 'Rochford',                            region: 'E' },
    { code: 'E07000076', name: 'Tendring',                            region: 'E' },
    { code: 'E07000077', name: 'Uttlesford',                          region: 'E' },
    { code: 'E07000078', name: 'Cheltenham',                          region: 'SW' },
    { code: 'E07000079', name: 'Cotswold',                            region: 'SW' },
    { code: 'E07000080', name: 'Forest of Dean',                      region: 'SW' },
    { code: 'E07000081', name: 'Gloucester',                          region: 'SW' },
    { code: 'E07000082', name: 'Stroud',                              region: 'SW' },
    { code: 'E07000083', name: 'Tewkesbury',                          region: 'SW' },
    { code: 'E07000084', name: 'Basingstoke and Deane',               region: 'SE' },
    { code: 'E07000085', name: 'East Hampshire',                      region: 'SE' },
    { code: 'E07000086', name: 'Eastleigh',                           region: 'SE' },
    { code: 'E07000087', name: 'Fareham',                             region: 'SE' },
    { code: 'E07000088', name: 'Gosport',                             region: 'SE' },
    { code: 'E07000089', name: 'Hart',                                region: 'SE' },
    { code: 'E07000090', name: 'Havant',                              region: 'SE' },
    { code: 'E07000091', name: 'New Forest',                          region: 'SE' },
    { code: 'E07000092', name: 'Rushmoor',                            region: 'SE' },
    { code: 'E07000093', name: 'Test Valley',                         region: 'SE' },
    { code: 'E07000094', name: 'Winchester',                          region: 'SE' },
    { code: 'E07000095', name: 'Broxbourne',                          region: 'E' },
    { code: 'E07000096', name: 'Dacorum',                             region: 'E' },
    { code: 'E07000098', name: 'Hertsmere',                           region: 'E' },
    { code: 'E07000099', name: 'North Hertfordshire',                 region: 'E' },
    { code: 'E07000102', name: 'Three Rivers',                        region: 'E' },
    { code: 'E07000103', name: 'Watford',                             region: 'E' },
    { code: 'E07000105', name: 'Ashford',                             region: 'SE' },
    { code: 'E07000106', name: 'Canterbury',                          region: 'SE' },
    { code: 'E07000107', name: 'Dartford',                            region: 'SE' },
    { code: 'E07000108', name: 'Dover',                               region: 'SE' },
    { code: 'E07000109', name: 'Gravesham',                           region: 'SE' },
    { code: 'E07000110', name: 'Maidstone',                           region: 'SE' },
    { code: 'E07000111', name: 'Sevenoaks',                           region: 'SE' },
    { code: 'E07000112', name: 'Folkestone and Hythe',                region: 'SE' },
    { code: 'E07000113', name: 'Swale',                               region: 'SE' },
    { code: 'E07000114', name: 'Thanet',                              region: 'SE' },
    { code: 'E07000115', name: 'Tonbridge and Malling',               region: 'SE' },
    { code: 'E07000116', name: 'Tunbridge Wells',                     region: 'SE' },
    { code: 'E07000117', name: 'Burnley',                             region: 'NW' },
    { code: 'E07000118', name: 'Chorley',                             region: 'NW' },
    { code: 'E07000119', name: 'Fylde',                               region: 'NW' },
    { code: 'E07000120', name: 'Hyndburn',                            region: 'NW' },
    { code: 'E07000121', name: 'Lancaster',                           region: 'NW' },
    { code: 'E07000122', name: 'Pendle',                              region: 'NW' },
    { code: 'E07000123', name: 'Preston',                             region: 'NW' },
    { code: 'E07000124', name: 'Ribble Valley',                       region: 'NW' },
    { code: 'E07000125', name: 'Rossendale',                          region: 'NW' },
    { code: 'E07000126', name: 'South Ribble',                        region: 'NW' },
    { code: 'E07000127', name: 'West Lancashire',                     region: 'NW' },
    { code: 'E07000128', name: 'Wyre',                                region: 'NW' },
    { code: 'E07000129', name: 'Blaby',                               region: 'EM' },
    { code: 'E07000130', name: 'Charnwood',                           region: 'EM' },
    { code: 'E07000131', name: 'Harborough',                          region: 'EM' },
    { code: 'E07000132', name: 'Hinckley and Bosworth',               region: 'EM' },
    { code: 'E07000133', name: 'Melton',                              region: 'EM' },
    { code: 'E07000134', name: 'North West Leicestershire',           region: 'EM' },
    { code: 'E07000135', name: 'Oadby and Wigston',                   region: 'EM' },
    { code: 'E07000136', name: 'Boston',                              region: 'EM' },
    { code: 'E07000137', name: 'East Lindsey',                        region: 'EM' },
    { code: 'E07000138', name: 'Lincoln',                             region: 'EM' },
    { code: 'E07000139', name: 'North Kesteven',                      region: 'EM' },
    { code: 'E07000140', name: 'South Holland',                       region: 'EM' },
    { code: 'E07000141', name: 'South Kesteven',                      region: 'EM' },
    { code: 'E07000142', name: 'West Lindsey',                        region: 'EM' },
    { code: 'E07000143', name: 'Breckland',                           region: 'E' },
    { code: 'E07000144', name: 'Broadland',                           region: 'E' },
    { code: 'E07000145', name: 'Great Yarmouth',                      region: 'E' },
    { code: 'E07000146', name: "King's Lynn and West Norfolk",        region: 'E' },
    { code: 'E07000147', name: 'North Norfolk',                       region: 'E' },
    { code: 'E07000148', name: 'Norwich',                             region: 'E' },
    { code: 'E07000149', name: 'South Norfolk',                       region: 'E' },
    { code: 'E07000163', name: 'Craven',                              region: 'YH' },
    { code: 'E07000164', name: 'Hambleton',                           region: 'YH' },
    { code: 'E07000165', name: 'Harrogate',                           region: 'YH' },
    { code: 'E07000166', name: 'Richmondshire',                       region: 'YH' },
    { code: 'E07000167', name: 'Ryedale',                             region: 'YH' },
    { code: 'E07000168', name: 'Scarborough',                         region: 'YH' },
    { code: 'E07000169', name: 'Selby',                               region: 'YH' },
    { code: 'E07000170', name: 'Ashfield',                            region: 'EM' },
    { code: 'E07000171', name: 'Bassetlaw',                           region: 'EM' },
    { code: 'E07000172', name: 'Broxtowe',                            region: 'EM' },
    { code: 'E07000173', name: 'Gedling',                             region: 'EM' },
    { code: 'E07000174', name: 'Mansfield',                           region: 'EM' },
    { code: 'E07000175', name: 'Newark and Sherwood',                 region: 'EM' },
    { code: 'E07000176', name: 'Rushcliffe',                          region: 'EM' },
    { code: 'E07000177', name: 'Cherwell',                            region: 'SE' },
    { code: 'E07000178', name: 'Oxford',                              region: 'SE' },
    { code: 'E07000179', name: 'South Oxfordshire',                   region: 'SE' },
    { code: 'E07000180', name: 'Vale of White Horse',                 region: 'SE' },
    { code: 'E07000181', name: 'West Oxfordshire',                    region: 'SE' },
    { code: 'E07000187', name: 'Mendip',                              region: 'SW' },
    { code: 'E07000188', name: 'Sedgemoor',                           region: 'SW' },
    { code: 'E07000189', name: 'South Somerset',                      region: 'SW' },
    { code: 'E07000192', name: 'Cannock Chase',                       region: 'WM' },
    { code: 'E07000193', name: 'East Staffordshire',                  region: 'WM' },
    { code: 'E07000194', name: 'Lichfield',                           region: 'WM' },
    { code: 'E07000195', name: 'Newcastle-under-Lyme',                region: 'WM' },
    { code: 'E07000196', name: 'South Staffordshire',                 region: 'WM' },
    { code: 'E07000197', name: 'Stafford',                            region: 'WM' },
    { code: 'E07000198', name: 'Staffordshire Moorlands',             region: 'WM' },
    { code: 'E07000199', name: 'Tamworth',                            region: 'WM' },
    { code: 'E07000200', name: 'Babergh',                             region: 'E' },
    { code: 'E07000202', name: 'Ipswich',                             region: 'E' },
    { code: 'E07000203', name: 'Mid Suffolk',                         region: 'E' },
    { code: 'E07000207', name: 'Elmbridge',                           region: 'SE' },
    { code: 'E07000208', name: 'Epsom and Ewell',                     region: 'SE' },
    { code: 'E07000209', name: 'Guildford',                           region: 'SE' },
    { code: 'E07000210', name: 'Mole Valley',                         region: 'SE' },
    { code: 'E07000211', name: 'Reigate and Banstead',                region: 'SE' },
    { code: 'E07000212', name: 'Runnymede',                           region: 'SE' },
    { code: 'E07000213', name: 'Spelthorne',                          region: 'SE' },
    { code: 'E07000214', name: 'Surrey Heath',                        region: 'SE' },
    { code: 'E07000215', name: 'Tandridge',                           region: 'SE' },
    { code: 'E07000216', name: 'Waverley',                            region: 'SE' },
    { code: 'E07000217', name: 'Woking',                              region: 'SE' },
    { code: 'E07000218', name: 'North Warwickshire',                  region: 'WM' },
    { code: 'E07000219', name: 'Nuneaton and Bedworth',               region: 'WM' },
    { code: 'E07000220', name: 'Rugby',                               region: 'WM' },
    { code: 'E07000221', name: 'Stratford-on-Avon',                   region: 'WM' },
    { code: 'E07000222', name: 'Warwick',                             region: 'WM' },
    { code: 'E07000223', name: 'Adur',                                region: 'SE' },
    { code: 'E07000224', name: 'Arun',                                region: 'SE' },
    { code: 'E07000225', name: 'Chichester',                          region: 'SE' },
    { code: 'E07000226', name: 'Crawley',                             region: 'SE' },
    { code: 'E07000227', name: 'Horsham',                             region: 'SE' },
    { code: 'E07000228', name: 'Mid Sussex',                          region: 'SE' },
    { code: 'E07000229', name: 'Worthing',                            region: 'SE' },
    { code: 'E07000234', name: 'Bromsgrove',                          region: 'WM' },
    { code: 'E07000235', name: 'Malvern Hills',                       region: 'WM' },
    { code: 'E07000236', name: 'Redditch',                            region: 'WM' },
    { code: 'E07000237', name: 'Worcester',                           region: 'WM' },
    { code: 'E07000238', name: 'Wychavon',                            region: 'WM' },
    { code: 'E07000239', name: 'Wyre Forest',                         region: 'WM' },
    { code: 'E07000240', name: 'St Albans',                           region: 'E' },
    { code: 'E07000241', name: 'Welwyn Hatfield',                     region: 'E' },
    { code: 'E07000242', name: 'East Hertfordshire',                  region: 'E' },
    { code: 'E07000243', name: 'Stevenage',                           region: 'E' },
    { code: 'E07000244', name: 'East Suffolk',                        region: 'E' },
    { code: 'E07000245', name: 'West Suffolk',                        region: 'E' },
    { code: 'E07000246', name: 'Somerset West and Taunton',           region: 'SW' },
    { code: 'E08000001', name: 'Bolton',                              region: 'NW' },
    { code: 'E08000002', name: 'Bury',                                region: 'NW' },
    { code: 'E08000003', name: 'Manchester',                          region: 'NW' },
    { code: 'E08000004', name: 'Oldham',                              region: 'NW' },
    { code: 'E08000005', name: 'Rochdale',                            region: 'NW' },
    { code: 'E08000006', name: 'Salford',                             region: 'NW' },
    { code: 'E08000007', name: 'Stockport',                           region: 'NW' },
    { code: 'E08000008', name: 'Tameside',                            region: 'NW' },
    { code: 'E08000009', name: 'Trafford',                            region: 'NW' },
    { code: 'E08000010', name: 'Wigan',                               region: 'NW' },
    { code: 'E08000011', name: 'Knowsley',                            region: 'NW' },
    { code: 'E08000012', name: 'Liverpool',                           region: 'NW' },
    { code: 'E08000013', name: 'St. Helens',                          region: 'NW' },
    { code: 'E08000014', name: 'Sefton',                              region: 'NW' },
    { code: 'E08000015', name: 'Wirral',                              region: 'NW' },
    { code: 'E08000016', name: 'Barnsley',                            region: 'YH' },
    { code: 'E08000017', name: 'Doncaster',                           region: 'YH' },
    { code: 'E08000018', name: 'Rotherham',                           region: 'YH' },
    { code: 'E08000019', name: 'Sheffield',                           region: 'YH' },
    { code: 'E08000021', name: 'Newcastle upon Tyne',                 region: 'NE' },
    { code: 'E08000022', name: 'North Tyneside',                      region: 'NE' },
    { code: 'E08000023', name: 'South Tyneside',                      region: 'NE' },
    { code: 'E08000024', name: 'Sunderland',                          region: 'NE' },
    { code: 'E08000025', name: 'Birmingham',                          region: 'WM' },
    { code: 'E08000026', name: 'Coventry',                            region: 'WM' },
    { code: 'E08000027', name: 'Dudley',                              region: 'WM' },
    { code: 'E08000028', name: 'Sandwell',                            region: 'WM' },
    { code: 'E08000029', name: 'Solihull',                            region: 'WM' },
    { code: 'E08000030', name: 'Walsall',                             region: 'WM' },
    { code: 'E08000031', name: 'Wolverhampton',                       region: 'WM' },
    { code: 'E08000032', name: 'Bradford',                            region: 'YH' },
    { code: 'E08000033', name: 'Calderdale',                          region: 'YH' },
    { code: 'E08000034', name: 'Kirklees',                            region: 'YH' },
    { code: 'E08000035', name: 'Leeds',                               region: 'YH' },
    { code: 'E08000036', name: 'Wakefield',                           region: 'YH' },
    { code: 'E08000037', name: 'Gateshead',                           region: 'NE' },
    { code: 'E09000001', name: 'City of London',                      region: 'L' },
    { code: 'E09000002', name: 'Barking and Dagenham',                region: 'L' },
    { code: 'E09000003', name: 'Barnet',                              region: 'L' },
    { code: 'E09000004', name: 'Bexley',                              region: 'L' },
    { code: 'E09000005', name: 'Brent',                               region: 'L' },
    { code: 'E09000006', name: 'Bromley',                             region: 'L' },
    { code: 'E09000007', name: 'Camden',                              region: 'L' },
    { code: 'E09000008', name: 'Croydon',                             region: 'L' },
    { code: 'E09000009', name: 'Ealing',                              region: 'L' },
    { code: 'E09000010', name: 'Enfield',                             region: 'L' },
    { code: 'E09000011', name: 'Greenwich',                           region: 'L' },
    { code: 'E09000012', name: 'Hackney',                             region: 'L' },
    { code: 'E09000013', name: 'Hammersmith and Fulham',              region: 'L' },
    { code: 'E09000014', name: 'Haringey',                            region: 'L' },
    { code: 'E09000015', name: 'Harrow',                              region: 'L' },
    { code: 'E09000016', name: 'Havering',                            region: 'L' },
    { code: 'E09000017', name: 'Hillingdon',                          region: 'L' },
    { code: 'E09000018', name: 'Hounslow',                            region: 'L' },
    { code: 'E09000019', name: 'Islington',                           region: 'L' },
    { code: 'E09000020', name: 'Kensington and Chelsea',              region: 'L' },
    { code: 'E09000021', name: 'Kingston upon Thames',                region: 'L' },
    { code: 'E09000022', name: 'Lambeth',                             region: 'L' },
    { code: 'E09000023', name: 'Lewisham',                            region: 'L' },
    { code: 'E09000024', name: 'Merton',                              region: 'L' },
    { code: 'E09000025', name: 'Newham',                              region: 'L' },
    { code: 'E09000026', name: 'Redbridge',                           region: 'L' },
    { code: 'E09000027', name: 'Richmond upon Thames',                region: 'L' },
    { code: 'E09000028', name: 'Southwark',                           region: 'L' },
    { code: 'E09000029', name: 'Sutton',                              region: 'L' },
    { code: 'E09000030', name: 'Tower Hamlets',                       region: 'L' },
    { code: 'E09000031', name: 'Waltham Forest',                      region: 'L' },
    { code: 'E09000032', name: 'Wandsworth',                          region: 'L' },
    { code: 'E09000033', name: 'Westminster',                         region: 'L' },
  ].freeze

  def self.lad_of_code(code)
    ENGLAND.detect { |lad| lad[:code] == code }
  end

  def self.names(*regions)
    list(*regions, field: :name)
  end

  def self.codes(*regions)
    list(*regions, field: :code)
  end

  def self.list(*regions, field:)
    lads = regions.empty? ? ENGLAND : ENGLAND.select { |lad| regions.include?(lad[:region]) }
    lads.map { |lad| lad[field] }
  end
end
